export const data = {
    "success": true,
    "data": {
        "student": {
            "Official Details": [
                {
                    "id": 150,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Official Details",
                    "name": "admission_number",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 151,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Official Details",
                    "name": "roll_number",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 162,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Official Details",
                    "name": "admission_date",
                    "type": "date",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "name": "Class",
                    "type": "select",
                    "field_value": "1, 2, 3, 4, 5, 6",
                    "belong_to": "student",
                    "group": "Official Details",
                    "is_required": true,
                    "bs_column": 3
                },
                {
                    "name": "Section",
                    "type": "select",
                    "field_value": "A, B",
                    "belong_to": "student",
                    "group": "Official Details",
                    "is_required": true,
                    "bs_column": 3
                }
            ],
            "Personal Details": [
                {
                    "id": 152,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "first_name",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 153,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "middle_name",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 154,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "last_name",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 155,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "gender",
                    "type": "select",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": "Male, Female",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 156,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "date_of_birth",
                    "type": "date",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 157,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "category",
                    "type": "select",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": "",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 158,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "religion",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 159,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "caste",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 160,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "mobile_number",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 161,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "email",
                    "type": "email",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 163,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "student_profile_photo_url",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 164,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "blood_group",
                    "type": "select",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": "A+, O+, B+, AB+, A-, O-, B-, AB-",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:15.000000Z",
                    "updated_at": "2024-02-03T14:48:15.000000Z"
                },
                {
                    "id": 165,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Personal Details",
                    "name": "aadhar_number",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                }
            ],
            "Address Details": [
                {
                    "id": 166,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Address Details",
                    "name": "current_address",
                    "type": "textarea",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                },
                {
                    "id": 167,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Address Details",
                    "name": "permanent_address",
                    "type": "textarea",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                }
            ],
            "Transport Details": [
                {
                    "id": 168,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Transport Details",
                    "name": "bus_facility_required?",
                    "type": "radio",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": "yes, no",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                }
            ],
            "Hostel Details": [
                {
                    "id": 169,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Hostel Details",
                    "name": "hostel_facility_required?",
                    "type": "radio",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": "yes, no",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                }
            ],
            "Miscellaneous Details": [
                {
                    "id": 170,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Miscellaneous Details",
                    "name": "physical_disability?",
                    "type": "radio",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": "yes, no",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                },
                {
                    "id": 171,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Miscellaneous Details",
                    "name": "if_any_physical_disability",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                },
                {
                    "id": 172,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Miscellaneous Details",
                    "name": "national_identification_number",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                },
                {
                    "id": 173,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Miscellaneous Details",
                    "name": "local_identification_number",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                },
                {
                    "id": 174,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Miscellaneous Details",
                    "name": "rte",
                    "type": "text",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": "yes, no",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                },
                {
                    "id": 175,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Miscellaneous Details",
                    "name": "note",
                    "type": "textarea",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                }
            ],
            "status": [
                {
                    "id": 176,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "status",
                    "name": "status",
                    "type": "hidden",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": "true, false",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:16.000000Z",
                    "updated_at": "2024-02-03T14:48:16.000000Z"
                },
                {
                    "id": 207,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "status",
                    "name": "parent_status",
                    "type": "hidden",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": "true, false",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:20.000000Z",
                    "updated_at": "2024-02-03T14:48:20.000000Z"
                },
                {
                    "id": 248,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "status",
                    "name": "staff_status",
                    "type": "hidden",
                    "belong_to": "student",
                    "bs_column": 3,
                    "is_required": 1,
                    "field_value": "true, false",
                    "show_in_table": null,
                    "visible_on_table": 1,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:21.000000Z",
                    "updated_at": "2024-02-03T14:48:21.000000Z"
                }
            ],
            "id Details": [
                {
                    "id": 177,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "id Details",
                    "name": "parent_id",
                    "type": "hidden",
                    "belong_to": "student",
                    "bs_column": 0,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                },
                {
                    "id": 178,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "id Details",
                    "name": "institute_id",
                    "type": "hidden",
                    "belong_to": "student",
                    "bs_column": 0,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                }
            ]
        },
        "parent": {
            "id Details": [
                {
                    "id": 179,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "id Details",
                    "name": "parent_institute_id",
                    "type": "hidden",
                    "belong_to": "parent",
                    "bs_column": 0,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                }
            ],
            "Parent Guardian Details": [
                {
                    "id": 180,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_name",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                },
                {
                    "id": 181,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_name",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                },
                {
                    "id": 182,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_occupation",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                },
                {
                    "id": 183,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_occupation",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                },
                {
                    "id": 184,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_phone",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:17.000000Z",
                    "updated_at": "2024-02-03T14:48:17.000000Z"
                },
                {
                    "id": 185,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_phone",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:18.000000Z",
                    "updated_at": "2024-02-03T14:48:18.000000Z"
                },
                {
                    "id": 186,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_email",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:18.000000Z",
                    "updated_at": "2024-02-03T14:48:18.000000Z"
                },
                {
                    "id": 187,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_email",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:18.000000Z",
                    "updated_at": "2024-02-03T14:48:18.000000Z"
                },
                {
                    "id": 188,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_qualification",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:18.000000Z",
                    "updated_at": "2024-02-03T14:48:18.000000Z"
                },
                {
                    "id": 189,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_qualification",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:18.000000Z",
                    "updated_at": "2024-02-03T14:48:18.000000Z"
                },
                {
                    "id": 190,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_aadhar_number",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:18.000000Z",
                    "updated_at": "2024-02-03T14:48:18.000000Z"
                },
                {
                    "id": 191,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_aadhar_number",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:18.000000Z",
                    "updated_at": "2024-02-03T14:48:18.000000Z"
                },
                {
                    "id": 192,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_annual_income",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 193,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_annual_income",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 194,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "father_photo",
                    "type": "file",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 195,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "mother_photo",
                    "type": "file",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 196,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_name",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 197,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_photo",
                    "type": "file",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 198,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_aadhar_number",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 199,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_occupation",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 200,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_annual_income",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:19.000000Z",
                    "updated_at": "2024-02-03T14:48:19.000000Z"
                },
                {
                    "id": 201,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_qualification",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:20.000000Z",
                    "updated_at": "2024-02-03T14:48:20.000000Z"
                },
                {
                    "id": 202,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_phone",
                    "type": "text",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 1,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:20.000000Z",
                    "updated_at": "2024-02-03T14:48:20.000000Z"
                },
                {
                    "id": 203,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_email",
                    "type": "email",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:20.000000Z",
                    "updated_at": "2024-02-03T14:48:20.000000Z"
                },
                {
                    "id": 204,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Details",
                    "name": "guardian_relation",
                    "type": "select",
                    "belong_to": "parent",
                    "bs_column": 4,
                    "is_required": 1,
                    "field_value": "father, mother, sister, brother, uncle, aunt, cousin, other, grandfather, grandmother",
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:20.000000Z",
                    "updated_at": "2024-02-03T14:48:20.000000Z"
                }
            ],
            "Parent Guardian Address Details": [
                {
                    "id": 205,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Address Details",
                    "name": "current_address",
                    "type": "textarea",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:20.000000Z",
                    "updated_at": "2024-02-03T14:48:20.000000Z"
                },
                {
                    "id": 206,
                    "institute_id": "fcf44082-4b8e-4703-b08c-4ae2d8407026",
                    "group": "Parent Guardian Address Details",
                    "name": "permanent_address",
                    "type": "textarea",
                    "belong_to": "parent",
                    "bs_column": 6,
                    "is_required": 0,
                    "field_value": null,
                    "show_in_table": null,
                    "visible_on_table": 0,
                    "weight": null,
                    "status": 1,
                    "created_at": "2024-02-03T14:48:20.000000Z",
                    "updated_at": "2024-02-03T14:48:20.000000Z"
                }
            ]
        }
    },
    "message": "Student Field found",
    "code": 200
};

export const baseUrl = 'https://destinaerp.in/public/api/v1';

export const sessionsData = [
    {
        "id": 1,
        "session": "2025-2666",
        "status": 1,
        "created_at": "2024-02-23T07:29:59.000000Z",
        "updated_at": "2024-02-23T12:25:37.000000Z"
    },
    {
        "id": 2,
        "session": "2025-21",
        "status": 1,
        "created_at": "2024-02-23T07:30:06.000000Z",
        "updated_at": "2024-02-23T07:30:06.000000Z"
    },
    {
        "id": 3,
        "session": "2025-22",
        "status": 1,
        "created_at": "2024-02-23T07:30:11.000000Z",
        "updated_at": "2024-02-23T07:30:11.000000Z"
    },
    {
        "id": 4,
        "session": "2025-23",
        "status": 1,
        "created_at": "2024-02-23T07:30:16.000000Z",
        "updated_at": "2024-02-23T07:30:16.000000Z"
    },
    {
        "id": 6,
        "session": "2025-2666",
        "status": 1,
        "created_at": "2024-02-23T07:29:59.000000Z",
        "updated_at": "2024-02-23T12:25:37.000000Z"
    },
    {
        "id": 7,
        "session": "2025-21",
        "status": 1,
        "created_at": "2024-02-23T07:30:06.000000Z",
        "updated_at": "2024-02-23T07:30:06.000000Z"
    },
    {
        "id": 8,
        "session": "2025-22",
        "status": 1,
        "created_at": "2024-02-23T07:30:11.000000Z",
        "updated_at": "2024-02-23T07:30:11.000000Z"
    },
    {
        "id": 9,
        "session": "2025-23",
        "status": 1,
        "created_at": "2024-02-23T07:30:16.000000Z",
        "updated_at": "2024-02-23T07:30:16.000000Z"
    }
];